resources:
  repositories:
    - repository: template # Friendly name
      type: github # Repo type
      name: amit-kumar-singh-5/devops # Repo path
      endpoint: github.com_amit-kumar-singh-5 # Service Connection for GitHub Installation Token
     
trigger:
  - master

pool: 
  name: 'Azure Pipelines'    
  vmImage: 'ubuntu-20.04'
  
steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform 0.12.3'


- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'AmitTerraformTesting'
    backendAzureRmResourceGroupName: 'terraform'
    backendAzureRmStorageAccountName: 'ammutfstate'
    backendAzureRmContainerName: 'tfstatess'
    backendAzureRmKey: 'test.terraform.tfstate'
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : azurerm init'
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceArm: 'AmitTerraformTesting'
    backendAzureRmResourceGroupName: 'terraform'
    backendAzureRmStorageAccountName: 'ammutfstate'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: '$(Build.DefinitionName)-test.terraform.tfstate'
    
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : azurerm plan'
  inputs:
    command: plan
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceArm: 'AmitTerraformTesting'
    backendAzureRmResourceGroupName: 'terraform'
    backendAzureRmStorageAccountName: 'ammutfstate'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: '$(Build.DefinitionName)-test.terraform.tfstate'
    varsFile: 'variables/test.tfvars'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : azurerm Apply'
  inputs:
    command: apply
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAzureRM: 'AmitTerraformTesting'
